name: Build LocalBeat

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli
      - name: Build Windows
        run: cargo tauri build
        working-directory: LocalBeat
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: LocalBeat-Windows-Installer
          path: LocalBeat/src-tauri/target/release/bundle/msi/*.msi

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli
      - name: Build Mac
        run: cargo tauri build
        working-directory: LocalBeat
      - name: Upload Mac Installer
        uses: actions/upload-artifact@v3
        with:
          name: LocalBeat-Mac-Installer
          path: LocalBeat/src-tauri/target/release/bundle/dmg/*.dmg
